# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Release Maven Package
on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      GITHUB_USER: ${{ github.actor }}
      GITHUB_TOKEN: ${{ secrets.ORG_MAVEN_PUBLISH_TOKEN }}
      REVISION: 1.0.${{github.run_number}}

    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build And Test
        run: mvn --batch-mode verify -Drevision=${{ env.REVISION }}

      - name: Deploy
        if: github.ref_name == 'main'
        run: mvn --batch-mode deploy -Drevision=${{ env.REVISION }}

